# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='new_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='old_size',
            field=models.IntegerField(default=0),
        ),
    ]
