# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imagemanagement', '0003_accesskey'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='accessKey',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
